server:
  port: 8763

spring:
  application:
    name: Service-Userlist
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.134:3306/smbms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ok
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd


eureka:
  client:
    service-url:
      defaultZone : http://192.168.1.134:8761/eureka/
  instance:
    prefer-ip-address: true


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zb.sp.entity
  configuration:
    auto-mapping-behavior: full